import Link from "next/link";
import { FinancialFacts } from "./queue";
import { ContextFields, DemoShell, Icon } from "./shell";
import { checkpointLabels, demoUrl, eventLabels, istTime, money, readableAction, reviewLabels, type DemoContext, type DemoSnapshot } from "./data";

export function DemoCase({ view, context }: { view: DemoSnapshot; context: DemoContext }) {
  const { pack, checkpoint } = view;
  const action = checkpoint.nextActions.find((item) => item.ownerRole === context.role)!;
  const expected = checkpoint.expected;
  return <DemoShell context={context} path={`/demo/cases/${pack.id}`} checkpoint={checkpoint.id}>
    <Link className="back-link" href={demoUrl("/demo", context)} aria-label="Back to work queue"><span aria-hidden="true">←</span> Back to work queue</Link>
    <div className="page-heading case-page-heading"><div><span className="eyebrow">{pack.id} · FICTIONAL DISCHARGE CASE</span><h1>{pack.title}</h1><p>Source-linked review, with separate facts for Billing and Finance.</p></div><span className="status-badge amber">Whole case remains open</span></div>
    <section className="checkpoint-panel" aria-label="Snapshot checkpoint"><div><Icon kind="clock" /><div><strong>View the case at a checkpoint</strong><p>{view.asOf ? `As of ${istTime(view.asOf.occurredAt)}` : "Snapshot time needs review"} · Future evidence is excluded</p></div></div><form method="get" action={`/demo/cases/${pack.id}`}><ContextFields context={context} /><label className="sr-only" htmlFor="checkpoint">Timeline checkpoint</label><select id="checkpoint" name="checkpoint" defaultValue={checkpoint.id}>{pack.checkpoints.map((item) => <option key={item.id} value={item.id}>{checkpointLabels[item.id] ?? item.id}</option>)}</select><button type="submit" className="filter-button">View checkpoint</button></form></section>
    <section className="owner-panel" aria-label="Owner and next action"><span className={`role-avatar ${context.role.toLowerCase()}`}>{context.role[0]}</span><div><span className="eyebrow">{action.ownerRole} · NEXT ACTION IN THIS PREVIEW</span><p>{readableAction(action.action)}</p></div><span className="preview-tag">Role preview</span></section>
    {checkpoint.reviewReasons.length > 0 && <section className="review-panel" aria-label="Review blockers"><Icon kind="review" /><div><h2>Resolve the evidence before confirmation</h2><ul>{checkpoint.reviewReasons.map((reason) => <li key={reason}>{reviewLabels[reason] ?? reason}</li>)}</ul><p>Unknown financial facts stay as needs review. A verified deposit can still be tracked.</p></div></section>}
    {checkpoint.invalidatedArtifacts && <section className="revision-panel" aria-label="Revised bill warning"><strong>Bill v{checkpoint.billVersion} is now authoritative.</strong><p>Earlier assessment, pack approval and response draft were invalidated. The earlier bill remains in the evidence history.</p></section>}
    <div className="section-heading"><h2>Money, with the distinctions that matter</h2><p>Predefined acceptance outcomes · no live rule calculation</p></div>
    <FinancialFacts view={view} />
    <div className="reconciliation-grid"><section className="detail-panel" aria-label="Billing reconciliation"><div className="panel-heading"><span className="summary-icon green"><Icon kind="receipt" /></span><h2>Billing reconciliation</h2></div><dl className="fact-list"><div><dt>Final bill snapshot</dt><dd>{money(checkpoint.financialInputs.grossBillPaise)}</dd></div><div><dt>Verified patient payments / deposit</dt><dd>{money(checkpoint.financialInputs.netPatientPaymentsPaise)}</dd></div><div><dt>Confirmed hospital reduction</dt><dd>{money(expected.confirmedHospitalReductionPaise)}</dd></div><div className="emphasized"><dt>Patient balance to collect</dt><dd>{money(expected.patientCollectPaise)}</dd></div><div><dt>Patient refund owed</dt><dd>{money(expected.patientRefundOwedPaise)}</dd></div></dl><p className="panel-footnote">{checkpoint.billingSignedOff ? "Billing sign-off is present in this snapshot. A refund owed still needs an authorized execution record." : "Billing sign-off is pending. An estimate or deposit does not establish the confirmed patient amount."}</p></section>
    <section className="detail-panel" aria-label="Finance follow-up"><div className="panel-heading"><span className="summary-icon blue"><Icon kind="receipt" /></span><h2>Finance follow-up</h2></div><dl className="fact-list"><div><dt>Authorized receivable remaining</dt><dd>{money(expected.authorizedReceivablePaise)}</dd></div><div><dt>Settlement state</dt><dd className="text-value">{checkpoint.expectedState.settlement.replaceAll("-", " ")}</dd></div><div><dt>Decision dispute</dt><dd className="text-value">{checkpoint.expectedState.decisionDispute.replaceAll("-", " ")}</dd></div></dl><p className="panel-footnote">A payer short payment or disputed deduction never automatically increases patient liability. Authorized receipts can reconcile while the case remains open.</p></section></div>
    <div className="case-detail-grid"><div className="case-detail-primary"><section className="detail-panel query-panel" aria-label="Current payer queries"><div className="panel-title"><h2>Current payer queries</h2><span className="count-badge">{view.queries.length}</span></div>{view.queries.length ? view.queries.map((query) => <div className="query-item" key={query.reference}><span className={`status-badge ${query.acknowledged ? "green" : "violet"}`}>{query.acknowledged ? "Response acknowledged" : "Awaiting acknowledged response"}</span><h3>{query.reference}</h3><p>{query.text}</p>{query.acknowledged && <div className="query-response"><strong>{query.responseReference}</strong><span>Source references: {query.responseSources.join(" · ")}</span></div>}</div>) : <p className="panel-footnote">No payer queries recorded at this checkpoint.</p>}</section>
    <section className="detail-panel" aria-label="Case timeline"><div className="panel-title"><h2>Case timeline</h2><span className="muted-label">IST · {view.events.length} events</span></div><p className="timeline-note">{view.elapsedMinutes === null ? "Resolution time needs review." : `Desk resolution ${view.resolutionConfirmed ? "confirmed in" : "open for"} ${view.elapsedMinutes} minutes at this snapshot.`} Includes payer wait and rework.</p><ol className="timeline">{view.events.map((event) => <li key={event.id}><span className="timeline-marker" /><div><span className="event-time">{istTime(event.occurredAt)} · {event.actorRole}</span><h3>{eventLabels[event.type] ?? event.type.replaceAll("-", " ")}</h3><span className="event-reference">{event.id}</span><p>Evidence: {event.evidenceRefs.join(" · ")}</p><span className="recorded-time">Recorded {istTime(event.recordedAt)}</span></div></li>)}</ol></section></div>
    <section className="detail-panel evidence-panel" aria-label="Available evidence"><div className="panel-title"><h2>Available evidence</h2><span className="count-badge">{view.documents.length}</span></div><p className="panel-footnote evidence-intro">Original fictional source snapshots, limited to this checkpoint. Expand a record to inspect its content.</p><div className="evidence-list">{view.documents.map((doc) => <details key={doc.id} className="evidence-item"><summary><span className="document-icon"><Icon kind="receipt" /></span><span><strong>{doc.kind.replaceAll("-", " ")}</strong><span>Version {doc.version} · page {doc.page}</span></span><span className="details-chevron" aria-hidden="true">⌄</span></summary><div className="evidence-content"><span className="event-reference">{doc.id}</span><pre>{JSON.stringify(doc.content, null, 2)}</pre></div></details>)}</div><div className="evidence-version"><span className="eyebrow">CURRENT SNAPSHOT</span><dl><div><dt>Authoritative bill</dt><dd>{checkpoint.authoritativeBillVersion === null ? "Needs review" : `v${checkpoint.authoritativeBillVersion}`}</dd></div><div><dt>Rule fixture</dt><dd>{checkpoint.ruleVersion}</dd></div><div><dt>Facts verified</dt><dd>{checkpoint.factsVerified ? "Yes" : "Needs review"}</dd></div></dl></div></section></div>
  </DemoShell>;
}

