"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import type { AdminData, PlatformData } from "@/server/admin";
import { DEFAULT_CALCULATION_VERSION } from "@/server/financial/rules";
import styles from "./desk.module.css";
import { paise } from "./financial-panel";

const roles = ["INSURANCE_EXECUTIVE", "TPA_EXECUTIVE", "CLAIM_VERIFIER", "BILLING_OFFICER", "FINANCE_OFFICER", "DOCTOR", "RECEPTIONIST", "REPORT_USER"];
function useAdministration(endpoint: string) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [invitation, setInvitation] = useState("");
  async function save(action: unknown) {
    setPending(true); setMessage(""); setInvitation("");
    try {
      const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(action) });
      const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "This change could not be saved.");
      setInvitation(result.url ?? ""); setMessage("Saved. Current access and rules will be checked on the next request."); router.refresh();
    } catch (error) { setMessage(error instanceof Error ? error.message : "This change could not be saved."); }
    finally { setPending(false); }
  }
  return { save, pending, message, invitation, invalid: (error: unknown) => setMessage(error instanceof Error ? error.message : "Check the supplied values.") };
}
const formData = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); return new FormData(event.currentTarget); };
function Field({ name, label, value = "", type = "text", required = true }: { name: string; label: string; value?: string; type?: string; required?: boolean }) {
  return <label className={styles.field}>{label}<input name={name} type={type} step={type === "number" ? "any" : undefined} defaultValue={value} required={required} maxLength={2000} /></label>;
}
function Reason() { return <Field name="reason" label="Reason for this change" />; }
function Status({ value }: { value: string }) { return <label className={styles.field}>Status<select name="status" defaultValue={value}><option>ACTIVE</option><option>INACTIVE</option></select></label>; }
export function AdminPanel({ data }: { data: AdminData }) {
  const action = useAdministration("/api/admin");
  return <>
    <div className={styles.heading}><div><h1>Hospital administration</h1><p>Manage {data.hospital.name}, staff access and reviewed policy rules.</p></div></div>
    {action.message && <p role="status" className={styles.alert}>{action.message}</p>}
    {action.invitation && <p className={styles.success}>Share this invitation privately with the intended staff member: <a href={action.invitation}>{action.invitation}</a></p>}
    <div className={styles.grid}>
      <section className={styles.card}><h2>Hospital details</h2><form className={styles.form} onSubmit={(event) => { const form = formData(event); void action.save({ type: "hospital", name: form.get("name"), reason: form.get("reason") }); }}><Field name="name" label="Hospital name" value={data.hospital.name} /><Reason /><button className={styles.button} disabled={action.pending}>Save hospital name</button></form></section>
      <section className={styles.card}><h2>Add a branch</h2><form className={styles.form} onSubmit={(event) => { const form = formData(event); void action.save({ type: "branch-create", code: form.get("code"), name: form.get("name") }); }}><Field name="code" label="Branch code" /><Field name="name" label="Branch name" /><button className={styles.button} disabled={action.pending}>Create branch</button></form></section>
      <section className={styles.card}><h2>Invite staff</h2><p className={styles.muted}>Invitations expire after 24 hours. Hospital administrator invitations grant authority across this hospital.</p><form className={styles.form} onSubmit={(event) => { const form = formData(event); void action.save({ type: "invite", email: form.get("email"), branchId: form.get("branch"), role: form.get("role") }); }}><Field name="email" label="Staff email" type="email" /><label className={styles.field}>Initial branch<select name="branch" required>{data.branches.filter((row) => row.status === "ACTIVE").map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label className={styles.field}>Role<select name="role" defaultValue="" required><option value="" disabled>Choose a role</option>{["HOSPITAL_ADMIN", ...roles].map((role) => <option key={role}>{role}</option>)}</select></label><button className={styles.button} disabled={action.pending}>Create invitation</button></form></section>
      <section className={styles.card}><h2>Assign branch access</h2><p className={styles.muted}>Hospital administrator authority is managed through administrator invitations and account disabling.</p><form className={styles.form} onSubmit={(event) => { const form = formData(event); void action.save({ type: "grant", userId: form.get("user"), branchId: form.get("branch"), role: form.get("role"), reason: form.get("reason") }); }}><label className={styles.field}>Staff member<select name="user" required>{data.staff.filter((row) => row.status === "ACTIVE" && !row.platform).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label className={styles.field}>Branch<select name="branch" required>{data.branches.filter((row) => row.status === "ACTIVE").map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></label><label className={styles.field}>Role<select name="role" defaultValue="" required><option value="" disabled>Choose a role</option>{roles.map((role) => <option key={role}>{role}</option>)}</select></label><Reason /><button className={styles.button} disabled={action.pending}>Grant branch access</button></form></section>
    </div>
    <section className={styles.card} style={{ marginTop: 20 }}><h2>Branches</h2><p className={styles.muted}>Making a branch inactive immediately removes staff access to its clinical work. Records are preserved.</p><div className={styles.grid}>{data.branches.map((branch) => <form className={styles.form} key={branch.id} onSubmit={(event) => { const form = formData(event); void action.save({ type: "branch", branchId: branch.id, name: form.get("name"), status: form.get("status"), reason: form.get("reason") }); }}><strong>{branch.code}</strong><Field name="name" label="Branch name" value={branch.name} /><Status value={branch.status} /><Reason /><button className={styles.secondary} disabled={action.pending}>Save branch {branch.code}</button></form>)}</div></section>
    <section className={styles.card} style={{ marginTop: 20 }}><h2>Staff and branch grants</h2><div className={styles.caseList}>{data.staff.filter((user) => !user.platform).map((user) => <article className={styles.context} key={user.id}><h3>{user.name}</h3><p>{user.email} · {user.status}</p>{data.grants.filter((grant) => grant.userId === user.id).map((grant) => <div key={`${grant.branchId}:${grant.role}`}><p>{data.branches.find((branch) => branch.id === grant.branchId)?.name} · {grant.role} · {grant.status}</p>{grant.status === "ACTIVE" && roles.includes(grant.role) && <form className={styles.form} onSubmit={(event) => { const form = formData(event); void action.save({ type: "revoke-grant", userId: user.id, branchId: grant.branchId, role: grant.role, reason: form.get("reason") }); }}><Reason /><button className={styles.secondary} disabled={action.pending}>Revoke {grant.role} access</button></form>}</div>)}{user.status === "ACTIVE" && user.id !== data.actorId && <button className={styles.secondary} style={{ marginTop: 16 }} disabled={action.pending} onClick={() => { void action.save({ type: "disable", userId: user.id }); }}>Disable staff account {user.name}</button>}</article>)}</div></section>
    <section className={styles.card} style={{ marginTop: 20 }}><h2>Recent invitations</h2>{data.invitations.length ? data.invitations.map((invite) => <div key={invite.id} className={styles.context}><p>{invite.email} · {invite.role} · {invite.status} · expires {new Date(invite.expiresAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST</p>{invite.status === "PENDING" && <button className={styles.secondary} disabled={action.pending} onClick={() => { void action.save({ type: "revoke-invitation", invitationId: invite.id }); }}>Revoke invitation for {invite.email}</button>}</div>) : <p>No invitations yet.</p>}</section>
    <section className={styles.card} style={{ marginTop: 20 }}><h2>Create a rule revision</h2><p className={styles.muted}>Rules only calculate an estimate. Approval of a rule is separate from payer authorization. Approved contents are immutable; create a replacement and retire the old version.</p><form className={styles.form} onSubmit={(event) => { const form = formData(event); try { void action.save({ type: "rule-create", policyId: form.get("policy"), name: form.get("name"), reason: form.get("reason"), rule: { version: DEFAULT_CALCULATION_VERSION, validFrom: form.get("from"), validTo: form.get("to"), deductiblePaise: paise(form.get("deductible")), copayBps: paise(form.get("copay")), benefitLimitPaise: paise(form.get("limit")), tariffCapsPaise: String(form.get("caps") ?? "").trim() ? String(form.get("caps")).split(",").map((value) => value.trim().toLowerCase() === "uncapped" ? null : paise(value)) : [] } }); } catch (error) { action.invalid(error); } }}><Field name="name" label="Revision name" /><label className={styles.field}>Policy<select name="policy">{data.policies.map((policy) => <option key={policy.id} value={policy.id}>{policy.name}</option>)}</select></label><div className={styles.twoFields}><Field name="from" label="Effective from" type="date" /><Field name="to" label="Effective to" type="date" /><Field name="deductible" label="Deductible (INR)" value="0" /><Field name="copay" label="Co-pay (%)" value="0" type="number" /><Field name="limit" label="Benefit limit (INR)" /></div><Field name="caps" label="Tariff caps in bill-line order (INR, comma separated; use uncapped)" required={false} /><p className={styles.muted}>Leave tariff caps blank for uncapped lines. Enter one cap or uncapped entry for each bill line when using caps. Bill exclusions and approved reductions remain separately evidenced.</p><Reason /><button className={styles.button} disabled={action.pending}>Create draft rule revision</button></form></section>
    <section className={styles.card} style={{ marginTop: 20 }}><h2>Rule revisions</h2>{data.rules.length ? <div className={styles.caseList}>{data.rules.map((rule) => <article className={styles.context} key={rule.id}><h3>{rule.name}</h3><p>{rule.status} · lifecycle version {rule.version} · {rule.rule.validFrom} to {rule.rule.validTo}</p><p>Calculation: {rule.rule.version} · policy {rule.policyId} · {rule.reason}</p>{rule.status !== "RETIRED" && <form className={styles.form} onSubmit={(event) => { const form = formData(event); void action.save({ type: "rule-state", ruleId: rule.id, expectedVersion: rule.version, status: rule.status === "DRAFT" ? "APPROVED" : "RETIRED", reason: form.get("reason") }); }}><Reason /><button className={styles.secondary} disabled={action.pending}>{rule.status === "DRAFT" ? "Approve" : "Retire"} rule {rule.name}</button></form>}</article>)}</div> : <p>No registered rules yet. Existing reviewed assessments remain available in case history.</p>}</section>
    <section className={styles.card} style={{ marginTop: 20 }}><h2>Rule lifecycle history</h2><ol className={styles.timeline}>{data.ruleHistory.map((event) => <li key={`${event.ruleId}:${event.version}`}><strong>{data.rules.find((rule) => rule.id === event.ruleId)?.name} · {event.status}</strong><p>Version {event.version} · staff {event.actorId} · {new Date(event.createdAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST</p><p>{event.reason}</p></li>)}</ol></section>
  </>;
}
export function PlatformPanel({ data }: { data: PlatformData }) {
  const action = useAdministration("/api/platform");
  return <><div className={styles.heading}><div><h1>Platform registry</h1><p>Maintain hospital and branch metadata. Clinical records and hospital financial reports require separate hospital staff authority.</p></div></div>{action.message && <p role="status" className={styles.alert}>{action.message}</p>}<section className={styles.card}><h2>Add hospital</h2><form className={styles.form} onSubmit={(event) => { const form = formData(event); void action.save({ type: "hospital-create", code: form.get("code"), name: form.get("name") }); }}><Field name="code" label="Hospital code" /><Field name="name" label="Hospital name" /><button className={styles.button} disabled={action.pending}>Create hospital registry entry</button></form></section><div className={styles.caseList} style={{ marginTop: 20 }}>{data.hospitals.map((hospital) => <section className={styles.card} key={hospital.id}><h2>{hospital.code}</h2><form className={styles.form} onSubmit={(event) => { const form = formData(event); void action.save({ type: "hospital", hospitalId: hospital.id, name: form.get("name"), status: form.get("status"), reason: form.get("reason") }); }}><Field name="name" label="Hospital name" value={hospital.name} /><Status value={hospital.status} /><Reason /><button className={styles.secondary} disabled={action.pending}>Save hospital {hospital.code}</button></form><div className={styles.grid}>{data.branches.filter((branch) => branch.hospitalId === hospital.id).map((branch) => <form key={branch.id} className={styles.form} onSubmit={(event) => { const form = formData(event); void action.save({ type: "branch", hospitalId: hospital.id, branchId: branch.id, name: form.get("name"), status: form.get("status"), reason: form.get("reason") }); }}><strong>{branch.code}</strong><Field name="name" label="Branch name" value={branch.name} /><Status value={branch.status} /><Reason /><button className={styles.secondary} disabled={action.pending}>Save branch {branch.code}</button></form>)}</div><form className={styles.form} onSubmit={(event) => { const form = formData(event); void action.save({ type: "branch-create", hospitalId: hospital.id, code: form.get("code"), name: form.get("name") }); }}><h3>Add branch to {hospital.name}</h3><Field name="code" label="New branch code" /><Field name="name" label="New branch name" /><button className={styles.button} disabled={action.pending}>Create branch for {hospital.code}</button></form></section>)}</div></>;
}
