import { sql } from "drizzle-orm";
import { bigint, boolean, check, date, foreignKey, index, integer, jsonb, numeric, pgTable, primaryKey, text, timestamp, unique, varchar } from "drizzle-orm/pg-core";
import { authUser } from "./auth-schema";

// Exact source money is NUMERIC INR rupees (driver strings); IDs remain bigint.
// Review: docs/schema/phase-4-review.md. All source tables are retained.

export const hospitals = pgTable("hospitals", {
  hospitalId: bigint("hospital_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  hospitalCode: varchar("hospital_code", { length: 30 }).notNull(),
  hospitalName: varchar("hospital_name", { length: 200 }).notNull(),
  registrationNo: varchar("registration_no", { length: 100 }),
  phone: varchar("phone", { length: 30 }),
  email: varchar("email", { length: 150 }),
  addressLine1: varchar("address_line1", { length: 255 }),
  addressLine2: varchar("address_line2", { length: 255 }),
  city: varchar("city", { length: 100 }),
  state: varchar("state", { length: 100 }),
  pincode: varchar("pincode", { length: 10 }),
  country: varchar("country", { length: 100 }).default("India"),
  status: varchar("status", { length: 50 }).notNull().default("ACTIVE"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  unique("uq_hospitals_hospital_code").on(table.hospitalCode),
  check("ck_hospitals_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
]);

export const departments = pgTable("departments", {
  departmentId: bigint("department_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  departmentCode: varchar("department_code", { length: 30 }).notNull(),
  departmentName: varchar("department_name", { length: 150 }).notNull(),
  description: text("description"),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
}, (table) => [
  unique("uq_department").on(table.hospitalId, table.departmentCode),
  unique("uq_departments_hospital_id_department_id").on(table.hospitalId, table.departmentId),
  check("ck_departments_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
  foreignKey({ name: "fk_department_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
]);

export const roles = pgTable("roles", {
  roleId: bigint("role_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  roleCode: varchar("role_code", { length: 50 }).notNull(),
  roleName: varchar("role_name", { length: 100 }).notNull(),
  description: text("description"),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
}, (table) => [
  unique("uq_roles_role_code").on(table.roleCode),
  check("ck_roles_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
]);

export const permissions = pgTable("permissions", {
  permissionId: bigint("permission_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  permissionCode: varchar("permission_code", { length: 100 }).notNull(),
  permissionName: varchar("permission_name", { length: 150 }).notNull(),
  moduleName: varchar("module_name", { length: 100 }).notNull(),
  actionName: varchar("action_name", { length: 50 }).notNull(),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
}, (table) => [
  unique("uq_permissions_permission_code").on(table.permissionCode),
  check("ck_permissions_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
]);

export const rolePermissions = pgTable("role_permissions", {
  roleId: bigint("role_id", { mode: "bigint" }).notNull(),
  permissionId: bigint("permission_id", { mode: "bigint" }).notNull(),
}, (table) => [
  primaryKey({ columns: [table.roleId, table.permissionId] }),
  index("ix_fk_rp_permission").on(table.permissionId),
  foreignKey({ name: "fk_rp_role", columns: [table.roleId], foreignColumns: [roles.roleId] }).onDelete("restrict"),
  foreignKey({ name: "fk_rp_permission", columns: [table.permissionId], foreignColumns: [permissions.permissionId] }).onDelete("restrict"),
]);

export const staff = pgTable("staff", {
  staffId: bigint("staff_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  departmentId: bigint("department_id", { mode: "bigint" }),
  employeeCode: varchar("employee_code", { length: 50 }).notNull(),
  firstName: varchar("first_name", { length: 100 }).notNull(),
  lastName: varchar("last_name", { length: 100 }),
  gender: varchar("gender", { length: 50 }).default("NA"),
  mobile: varchar("mobile", { length: 20 }),
  email: varchar("email", { length: 150 }),
  designation: varchar("designation", { length: 120 }),
  joiningDate: date("joining_date"),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
}, (table) => [
  unique("uq_staff_employee").on(table.hospitalId, table.employeeCode),
  unique("uq_staff_hospital_id_staff_id").on(table.hospitalId, table.staffId),
  index("ix_fk_staff_department").on(table.hospitalId, table.departmentId),
  check("ck_staff_gender", sql`${table.gender} IN ('MALE', 'FEMALE', 'OTHER', 'NA')`),
  check("ck_staff_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')`),
  foreignKey({ name: "fk_staff_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_staff_department", columns: [table.hospitalId, table.departmentId], foreignColumns: [departments.hospitalId, departments.departmentId] }).onDelete("restrict"),
]);

export const users = pgTable("users", {
  userId: bigint("user_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  staffId: bigint("staff_id", { mode: "bigint" }),
  username: varchar("username", { length: 100 }).notNull(),
  email: varchar("email", { length: 150 }),
  lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  authUserId: text("auth_user_id"),
}, (table) => [
  unique("uq_users_username").on(table.username),
  unique("uq_users_hospital_id_user_id").on(table.hospitalId, table.userId),
  unique("uq_users_auth_identity").on(table.authUserId),
  index("ix_fk_user_staff").on(table.hospitalId, table.staffId),
  check("ck_users_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE', 'LOCKED')`),
  check("ck_users_active_identity", sql`${table.status} <> 'ACTIVE' OR ${table.authUserId} IS NOT NULL`),
  foreignKey({ name: "fk_user_staff", columns: [table.hospitalId, table.staffId], foreignColumns: [staff.hospitalId, staff.staffId] }).onDelete("restrict"),
  foreignKey({ name: "fk_users_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_users_auth_identity", columns: [table.authUserId], foreignColumns: [authUser.id] }).onDelete("restrict"),
]);

export const userRoles = pgTable("user_roles", {
  userId: bigint("user_id", { mode: "bigint" }).notNull(),
  roleId: bigint("role_id", { mode: "bigint" }).notNull(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
}, (table) => [
  primaryKey({ columns: [table.hospitalId, table.userId, table.roleId] }),
  index("ix_fk_ur_role").on(table.roleId),
  foreignKey({ name: "fk_ur_user", columns: [table.hospitalId, table.userId], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_ur_role", columns: [table.roleId], foreignColumns: [roles.roleId] }).onDelete("restrict"),
  foreignKey({ name: "fk_user_roles_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
]);

export const patients = pgTable("patients", {
  patientId: bigint("patient_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  patientCode: varchar("patient_code", { length: 50 }).notNull(),
  firstName: varchar("first_name", { length: 100 }).notNull(),
  middleName: varchar("middle_name", { length: 100 }),
  lastName: varchar("last_name", { length: 100 }),
  dateOfBirth: date("date_of_birth"),
  gender: varchar("gender", { length: 50 }).default("NA"),
  mobile: varchar("mobile", { length: 20 }),
  email: varchar("email", { length: 150 }),
  bloodGroup: varchar("blood_group", { length: 10 }),
  addressLine1: varchar("address_line1", { length: 255 }),
  addressLine2: varchar("address_line2", { length: 255 }),
  city: varchar("city", { length: 100 }),
  state: varchar("state", { length: 100 }),
  pincode: varchar("pincode", { length: 10 }),
  emergencyContactName: varchar("emergency_contact_name", { length: 150 }),
  emergencyContactMobile: varchar("emergency_contact_mobile", { length: 20 }),
  identityType: varchar("identity_type", { length: 50 }),
  identityNumber: varchar("identity_number", { length: 100 }),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
}, (table) => [
  unique("uq_patient_code").on(table.hospitalId, table.patientCode),
  unique("uq_patients_hospital_id_patient_id").on(table.hospitalId, table.patientId),
  index("idx_patient_mobile").on(table.mobile),
  index("idx_patient_name").on(table.lastName, table.firstName),
  index("ix_patient_hospital_mobile").on(table.hospitalId, table.mobile),
  check("ck_patients_gender", sql`${table.gender} IN ('MALE', 'FEMALE', 'OTHER', 'NA')`),
  check("ck_patients_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
  foreignKey({ name: "fk_patient_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
]);

export const patientDocuments = pgTable("patient_documents", {
  documentId: bigint("document_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  patientId: bigint("patient_id", { mode: "bigint" }).notNull(),
  documentType: varchar("document_type", { length: 100 }).notNull(),
  documentName: varchar("document_name", { length: 255 }).notNull(),
  filePath: varchar("file_path", { length: 500 }),
  fileHash: varchar("file_hash", { length: 128 }),
  uploadedBy: bigint("uploaded_by", { mode: "bigint" }),
  uploadedAt: timestamp("uploaded_at", { withTimezone: true }).defaultNow(),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
}, (table) => [
  unique("uq_patient_documents_hospital_id_document_id").on(table.hospitalId, table.documentId),
  index("ix_fk_pd_patient").on(table.hospitalId, table.patientId),
  index("ix_fk_pd_user").on(table.hospitalId, table.uploadedBy),
  check("ck_patient_documents_status", sql`${table.status} IN ('ACTIVE', 'ARCHIVED')`),
  foreignKey({ name: "fk_pd_patient", columns: [table.hospitalId, table.patientId], foreignColumns: [patients.hospitalId, patients.patientId] }).onDelete("restrict"),
  foreignKey({ name: "fk_pd_user", columns: [table.hospitalId, table.uploadedBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_patient_documents_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
]);

export const insuranceCategories = pgTable("insurance_categories", {
  insuranceCategoryId: bigint("insurance_category_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  categoryCode: varchar("category_code", { length: 50 }).notNull(),
  categoryName: varchar("category_name", { length: 150 }).notNull(),
  description: text("description"),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
}, (table) => [
  unique("uq_insurance_categories_category_code").on(table.categoryCode),
  check("ck_insurance_categories_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
]);

export const insuranceSubcategories = pgTable("insurance_subcategories", {
  insuranceSubcategoryId: bigint("insurance_subcategory_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  insuranceCategoryId: bigint("insurance_category_id", { mode: "bigint" }).notNull(),
  subcategoryCode: varchar("subcategory_code", { length: 50 }).notNull(),
  subcategoryName: varchar("subcategory_name", { length: 150 }).notNull(),
  description: text("description"),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
}, (table) => [
  unique("uq_ins_subcategory").on(table.insuranceCategoryId, table.subcategoryCode),
  check("ck_insurance_subcategories_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
  foreignKey({ name: "fk_ins_subcategory_category", columns: [table.insuranceCategoryId], foreignColumns: [insuranceCategories.insuranceCategoryId] }).onDelete("restrict"),
]);

export const insuranceCompanies = pgTable("insurance_companies", {
  insuranceCompanyId: bigint("insurance_company_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  companyCode: varchar("company_code", { length: 50 }).notNull(),
  companyName: varchar("company_name", { length: 200 }).notNull(),
  companyType: varchar("company_type", { length: 50 }).default("PRIVATE"),
  licenseNo: varchar("license_no", { length: 100 }),
  contactPerson: varchar("contact_person", { length: 150 }),
  phone: varchar("phone", { length: 30 }),
  email: varchar("email", { length: 150 }),
  website: varchar("website", { length: 255 }),
  address: text("address"),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
}, (table) => [
  unique("uq_insurance_companies_company_code").on(table.companyCode),
  check("ck_insurance_companies_company_type", sql`${table.companyType} IN ('GOVERNMENT', 'PRIVATE', 'PSU', 'INTERNATIONAL', 'OTHER')`),
  check("ck_insurance_companies_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
]);

export const tpas = pgTable("tpas", {
  tpaId: bigint("tpa_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  tpaCode: varchar("tpa_code", { length: 50 }).notNull(),
  tpaName: varchar("tpa_name", { length: 200 }).notNull(),
  licenseNo: varchar("license_no", { length: 100 }),
  contactPerson: varchar("contact_person", { length: 150 }),
  phone: varchar("phone", { length: 30 }),
  email: varchar("email", { length: 150 }),
  website: varchar("website", { length: 255 }),
  address: text("address"),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
}, (table) => [
  unique("uq_tpas_tpa_code").on(table.tpaCode),
  check("ck_tpas_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
]);

export const insuranceCompanyTpas = pgTable("insurance_company_tpas", {
  insuranceCompanyId: bigint("insurance_company_id", { mode: "bigint" }).notNull(),
  tpaId: bigint("tpa_id", { mode: "bigint" }).notNull(),
  effectiveFrom: date("effective_from"),
  effectiveTo: date("effective_to"),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
}, (table) => [
  primaryKey({ columns: [table.insuranceCompanyId, table.tpaId] }),
  index("ix_fk_ict_tpa").on(table.tpaId),
  check("ck_insurance_company_tpas_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
  check("ck_insurance_company_tpas_effective_from_effective_to", sql`${table.effectiveTo} >= ${table.effectiveFrom}`),
  foreignKey({ name: "fk_ict_company", columns: [table.insuranceCompanyId], foreignColumns: [insuranceCompanies.insuranceCompanyId] }).onDelete("restrict"),
  foreignKey({ name: "fk_ict_tpa", columns: [table.tpaId], foreignColumns: [tpas.tpaId] }).onDelete("restrict"),
]);

export const insurancePolicies = pgTable("insurance_policies", {
  policyId: bigint("policy_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  insuranceCompanyId: bigint("insurance_company_id", { mode: "bigint" }).notNull(),
  tpaId: bigint("tpa_id", { mode: "bigint" }),
  insuranceSubcategoryId: bigint("insurance_subcategory_id", { mode: "bigint" }),
  policyCode: varchar("policy_code", { length: 80 }).notNull(),
  planName: varchar("plan_name", { length: 200 }).notNull(),
  policyType: varchar("policy_type", { length: 50 }).default("INDIVIDUAL"),
  coverageLimit: numeric("coverage_limit", { precision: 15, scale: 2 }),
  roomRentLimit: numeric("room_rent_limit", { precision: 15, scale: 2 }),
  icuLimit: numeric("icu_limit", { precision: 15, scale: 2 }),
  copayPercent: numeric("copay_percent", { precision: 5, scale: 2 }).default("0"),
  deductibleAmount: numeric("deductible_amount", { precision: 15, scale: 2 }),
  cashlessAllowed: boolean("cashless_allowed").default(true),
  reimbursementAllowed: boolean("reimbursement_allowed").default(true),
  validFrom: date("valid_from"),
  validTo: date("valid_to"),
  termsText: text("terms_text"),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
}, (table) => [
  check("ck_insurance_policies_coverage_limit_finite", sql`${table.coverageLimit} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_insurance_policies_room_rent_limit_finite", sql`${table.roomRentLimit} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_insurance_policies_icu_limit_finite", sql`${table.icuLimit} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_insurance_policies_copay_percent_finite", sql`${table.copayPercent} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_insurance_policies_deductible_amount_finite", sql`${table.deductibleAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_insurance_policies_policy_code").on(table.policyCode),
  index("ix_fk_policy_company").on(table.insuranceCompanyId),
  index("ix_fk_policy_tpa").on(table.tpaId),
  index("ix_fk_policy_subcategory").on(table.insuranceSubcategoryId),
  index("ix_fk_policy_company_tpa_pair").on(table.insuranceCompanyId, table.tpaId),
  check("ck_insurance_policies_policy_type", sql`${table.policyType} IN ('INDIVIDUAL', 'FAMILY_FLOATER', 'CORPORATE', 'GROUP', 'GOVERNMENT', 'ACCIDENT', 'CRITICAL_ILLNESS', 'MATERNITY', 'TRAVEL', 'INTERNATIONAL', 'OTHER')`),
  check("ck_insurance_policies_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
  check("ck_insurance_policies_coverage_limit_nonnegative", sql`${table.coverageLimit} >= 0`),
  check("ck_insurance_policies_room_rent_limit_nonnegative", sql`${table.roomRentLimit} >= 0`),
  check("ck_insurance_policies_icu_limit_nonnegative", sql`${table.icuLimit} >= 0`),
  check("ck_insurance_policies_copay_percent_range", sql`${table.copayPercent} BETWEEN 0 AND 100`),
  check("ck_insurance_policies_deductible_amount_nonnegative", sql`${table.deductibleAmount} >= 0`),
  check("ck_insurance_policies_valid_from_valid_to", sql`${table.validTo} >= ${table.validFrom}`),
  foreignKey({ name: "fk_policy_company", columns: [table.insuranceCompanyId], foreignColumns: [insuranceCompanies.insuranceCompanyId] }).onDelete("restrict"),
  foreignKey({ name: "fk_policy_tpa", columns: [table.tpaId], foreignColumns: [tpas.tpaId] }).onDelete("restrict"),
  foreignKey({ name: "fk_policy_subcategory", columns: [table.insuranceSubcategoryId], foreignColumns: [insuranceSubcategories.insuranceSubcategoryId] }).onDelete("restrict"),
  foreignKey({ name: "fk_policy_company_tpa_pair", columns: [table.insuranceCompanyId, table.tpaId], foreignColumns: [insuranceCompanyTpas.insuranceCompanyId, insuranceCompanyTpas.tpaId] }).onDelete("restrict"),
]);

export const patientInsurance = pgTable("patient_insurance", {
  patientInsuranceId: bigint("patient_insurance_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  patientId: bigint("patient_id", { mode: "bigint" }).notNull(),
  policyId: bigint("policy_id", { mode: "bigint" }).notNull(),
  memberId: varchar("member_id", { length: 100 }),
  policyNumber: varchar("policy_number", { length: 100 }).notNull(),
  relationshipToHolder: varchar("relationship_to_holder", { length: 50 }),
  insuredName: varchar("insured_name", { length: 200 }),
  validFrom: date("valid_from"),
  validTo: date("valid_to"),
  sumInsured: numeric("sum_insured", { precision: 15, scale: 2 }),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
  verificationStatus: varchar("verification_status", { length: 50 }).default("NOT_VERIFIED"),
  verificationAt: timestamp("verification_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
}, (table) => [
  check("ck_patient_insurance_sum_insured_finite", sql`${table.sumInsured} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_patient_policy").on(table.patientId, table.policyNumber),
  unique("uq_patient_insurance_hospital_id_patient_insurance_id").on(table.hospitalId, table.patientInsuranceId),
  unique("uq_patient_insurance_hospital_id_patient_id_patient_insurance_id").on(table.hospitalId, table.patientId, table.patientInsuranceId),
  index("idx_policy_number").on(table.policyNumber),
  index("ix_fk_pi_policy").on(table.policyId),
  check("ck_patient_insurance_status", sql`${table.status} IN ('ACTIVE', 'EXPIRED', 'SUSPENDED', 'CANCELLED')`),
  check("ck_patient_insurance_verification_status", sql`${table.verificationStatus} IN ('NOT_VERIFIED', 'PENDING', 'VERIFIED', 'FAILED')`),
  check("ck_patient_insurance_sum_insured_nonnegative", sql`${table.sumInsured} >= 0`),
  check("ck_patient_insurance_valid_from_valid_to", sql`${table.validTo} >= ${table.validFrom}`),
  foreignKey({ name: "fk_pi_patient", columns: [table.hospitalId, table.patientId], foreignColumns: [patients.hospitalId, patients.patientId] }).onDelete("restrict"),
  foreignKey({ name: "fk_pi_policy", columns: [table.policyId], foreignColumns: [insurancePolicies.policyId] }).onDelete("restrict"),
  foreignKey({ name: "fk_patient_insurance_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
]);

export const appointments = pgTable("appointments", {
  appointmentId: bigint("appointment_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  patientId: bigint("patient_id", { mode: "bigint" }).notNull(),
  departmentId: bigint("department_id", { mode: "bigint" }),
  doctorStaffId: bigint("doctor_staff_id", { mode: "bigint" }),
  appointmentNo: varchar("appointment_no", { length: 60 }).notNull(),
  appointmentDatetime: timestamp("appointment_datetime", { withTimezone: true }).notNull(),
  appointmentType: varchar("appointment_type", { length: 50 }).default("OPD"),
  reason: text("reason"),
  status: varchar("status", { length: 50 }).default("BOOKED"),
  createdBy: bigint("created_by", { mode: "bigint" }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  unique("uq_appointments_appointment_no").on(table.appointmentNo),
  unique("uq_appointments_hospital_id_appointment_id").on(table.hospitalId, table.appointmentId),
  unique("uq_appointments_hospital_id_branch_id_appointment_id").on(table.hospitalId, table.branchId, table.appointmentId),
  unique("uq_appointments_hospital_id_branch_id_patient_id_appointment_id").on(table.hospitalId, table.branchId, table.patientId, table.appointmentId),
  index("ix_fk_appt_patient").on(table.hospitalId, table.patientId),
  index("ix_fk_appt_department").on(table.hospitalId, table.departmentId),
  index("ix_fk_appt_doctor").on(table.hospitalId, table.doctorStaffId),
  index("ix_fk_appt_user").on(table.hospitalId, table.createdBy),
  check("ck_appointments_appointment_type", sql`${table.appointmentType} IN ('OPD', 'FOLLOWUP', 'EMERGENCY', 'TELEMEDICINE', 'OTHER')`),
  check("ck_appointments_status", sql`${table.status} IN ('BOOKED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')`),
  foreignKey({ name: "fk_appt_patient", columns: [table.hospitalId, table.patientId], foreignColumns: [patients.hospitalId, patients.patientId] }).onDelete("restrict"),
  foreignKey({ name: "fk_appt_department", columns: [table.hospitalId, table.departmentId], foreignColumns: [departments.hospitalId, departments.departmentId] }).onDelete("restrict"),
  foreignKey({ name: "fk_appt_doctor", columns: [table.hospitalId, table.doctorStaffId], foreignColumns: [staff.hospitalId, staff.staffId] }).onDelete("restrict"),
  foreignKey({ name: "fk_appt_user", columns: [table.hospitalId, table.createdBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_appointments_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_appointments_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const encounters = pgTable("encounters", {
  encounterId: bigint("encounter_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  patientId: bigint("patient_id", { mode: "bigint" }).notNull(),
  appointmentId: bigint("appointment_id", { mode: "bigint" }),
  encounterNo: varchar("encounter_no", { length: 60 }).notNull(),
  admissionDate: timestamp("admission_date", { withTimezone: true }),
  dischargeDate: timestamp("discharge_date", { withTimezone: true }),
  encounterType: varchar("encounter_type", { length: 50 }).default("OPD"),
  diagnosis: text("diagnosis"),
  clinicalNotes: text("clinical_notes"),
  status: varchar("status", { length: 50 }).default("OPEN"),
  createdBy: bigint("created_by", { mode: "bigint" }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  unique("uq_encounters_encounter_no").on(table.encounterNo),
  unique("uq_encounters_hospital_id_encounter_id").on(table.hospitalId, table.encounterId),
  unique("uq_encounters_hospital_id_branch_id_encounter_id").on(table.hospitalId, table.branchId, table.encounterId),
  unique("uq_encounters_hospital_id_branch_id_patient_id_encounter_id").on(table.hospitalId, table.branchId, table.patientId, table.encounterId),
  index("ix_fk_enc_patient").on(table.hospitalId, table.patientId),
  index("ix_fk_enc_appt").on(table.hospitalId, table.branchId, table.patientId, table.appointmentId),
  index("ix_fk_enc_user").on(table.hospitalId, table.createdBy),
  check("ck_encounters_encounter_type", sql`${table.encounterType} IN ('OPD', 'IPD', 'EMERGENCY', 'DAYCARE', 'OTHER')`),
  check("ck_encounters_status", sql`${table.status} IN ('OPEN', 'CLOSED', 'CANCELLED')`),
  check("ck_encounters_admission_date_discharge_date", sql`${table.dischargeDate} >= ${table.admissionDate}`),
  foreignKey({ name: "fk_enc_patient", columns: [table.hospitalId, table.patientId], foreignColumns: [patients.hospitalId, patients.patientId] }).onDelete("restrict"),
  foreignKey({ name: "fk_enc_appt", columns: [table.hospitalId, table.branchId, table.patientId, table.appointmentId], foreignColumns: [appointments.hospitalId, appointments.branchId, appointments.patientId, appointments.appointmentId] }).onDelete("restrict"),
  foreignKey({ name: "fk_enc_user", columns: [table.hospitalId, table.createdBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_encounters_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_encounters_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const treatmentServices = pgTable("treatment_services", {
  serviceId: bigint("service_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  serviceCode: varchar("service_code", { length: 50 }).notNull(),
  serviceName: varchar("service_name", { length: 200 }).notNull(),
  serviceCategory: varchar("service_category", { length: 100 }),
  standardCharge: numeric("standard_charge", { precision: 15, scale: 2 }),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
}, (table) => [
  check("ck_treatment_services_standard_charge_finite", sql`${table.standardCharge} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_treatment_services_service_code").on(table.serviceCode),
  check("ck_treatment_services_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
  check("ck_treatment_services_standard_charge_nonnegative", sql`${table.standardCharge} >= 0`),
]);

export const encounterServices = pgTable("encounter_services", {
  encounterServiceId: bigint("encounter_service_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  encounterId: bigint("encounter_id", { mode: "bigint" }).notNull(),
  serviceId: bigint("service_id", { mode: "bigint" }).notNull(),
  serviceDate: timestamp("service_date", { withTimezone: true }).notNull(),
  quantity: numeric("quantity", { precision: 10, scale: 2 }).default("1"),
  unitCharge: numeric("unit_charge", { precision: 15, scale: 2 }).notNull(),
  discountAmount: numeric("discount_amount", { precision: 15, scale: 2 }),
  taxAmount: numeric("tax_amount", { precision: 15, scale: 2 }),
  netAmount: numeric("net_amount", { precision: 15, scale: 2 }).notNull(),
  clinicalNote: text("clinical_note"),
  createdBy: bigint("created_by", { mode: "bigint" }),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  check("ck_encounter_services_quantity_finite", sql`${table.quantity} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_encounter_services_unit_charge_finite", sql`${table.unitCharge} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_encounter_services_discount_amount_finite", sql`${table.discountAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_encounter_services_tax_amount_finite", sql`${table.taxAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_encounter_services_net_amount_finite", sql`${table.netAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_encounter_services_hospital_id_encounter_service_id").on(table.hospitalId, table.encounterServiceId),
  unique("uq_encounter_services_hospital_id_branch_id_encounter_service_id").on(table.hospitalId, table.branchId, table.encounterServiceId),
  index("ix_fk_es_encounter").on(table.hospitalId, table.branchId, table.encounterId),
  index("ix_fk_es_service").on(table.serviceId),
  index("ix_fk_es_user").on(table.hospitalId, table.createdBy),
  check("ck_encounter_services_quantity_positive", sql`${table.quantity} > 0`),
  check("ck_encounter_services_unit_charge_nonnegative", sql`${table.unitCharge} >= 0`),
  check("ck_encounter_services_discount_amount_nonnegative", sql`${table.discountAmount} >= 0`),
  check("ck_encounter_services_tax_amount_nonnegative", sql`${table.taxAmount} >= 0`),
  check("ck_encounter_services_net_amount_nonnegative", sql`${table.netAmount} >= 0`),
  foreignKey({ name: "fk_es_encounter", columns: [table.hospitalId, table.branchId, table.encounterId], foreignColumns: [encounters.hospitalId, encounters.branchId, encounters.encounterId] }).onDelete("restrict"),
  foreignKey({ name: "fk_es_service", columns: [table.serviceId], foreignColumns: [treatmentServices.serviceId] }).onDelete("restrict"),
  foreignKey({ name: "fk_es_user", columns: [table.hospitalId, table.createdBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_encounter_services_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_encounter_services_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const claims = pgTable("claims", {
  claimId: bigint("claim_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  claimNo: varchar("claim_no", { length: 80 }).notNull(),
  patientId: bigint("patient_id", { mode: "bigint" }).notNull(),
  patientInsuranceId: bigint("patient_insurance_id", { mode: "bigint" }).notNull(),
  encounterId: bigint("encounter_id", { mode: "bigint" }),
  claimType: varchar("claim_type", { length: 50 }).notNull(),
  claimStage: varchar("claim_stage", { length: 50 }).default("REGISTERED"),
  claimStatus: varchar("claim_status", { length: 50 }).default("DRAFT"),
  admissionDate: timestamp("admission_date", { withTimezone: true }),
  dischargeDate: timestamp("discharge_date", { withTimezone: true }),
  estimatedAmount: numeric("estimated_amount", { precision: 15, scale: 2 }),
  claimedAmount: numeric("claimed_amount", { precision: 15, scale: 2 }),
  approvedAmount: numeric("approved_amount", { precision: 15, scale: 2 }),
  rejectedAmount: numeric("rejected_amount", { precision: 15, scale: 2 }),
  patientPayableAmount: numeric("patient_payable_amount", { precision: 15, scale: 2 }),
  remarks: text("remarks"),
  createdBy: bigint("created_by", { mode: "bigint" }),
  assignedTo: bigint("assigned_to", { mode: "bigint" }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
  version: integer("version").notNull().default(1),
  nextAction: text("next_action"),
  dueAt: timestamp("due_at", { withTimezone: true }),
  creationKey: varchar("creation_key", { length: 150 }),
  creationFingerprint: text("creation_fingerprint"),
}, (table) => [
  check("ck_claims_estimated_amount_finite", sql`${table.estimatedAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_claims_claimed_amount_finite", sql`${table.claimedAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_claims_approved_amount_finite", sql`${table.approvedAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_claims_rejected_amount_finite", sql`${table.rejectedAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_claims_patient_payable_amount_finite", sql`${table.patientPayableAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_claims_claim_no").on(table.claimNo),
  unique("uq_claims_hospital_id_claim_id").on(table.hospitalId, table.claimId),
  unique("uq_claims_hospital_id_branch_id_claim_id").on(table.hospitalId, table.branchId, table.claimId),
  unique("uq_claims_hospital_id_branch_id_patient_id_claim_id").on(table.hospitalId, table.branchId, table.patientId, table.claimId),
  unique("uq_claim_creation_key").on(table.hospitalId, table.branchId, table.creationKey),
  index("idx_claim_status").on(table.claimStatus),
  index("idx_claim_stage").on(table.claimStage),
  index("idx_claim_patient").on(table.patientId),
  index("ix_fk_claim_patient").on(table.hospitalId, table.patientId),
  index("ix_fk_claim_patient_insurance").on(table.hospitalId, table.patientId, table.patientInsuranceId),
  index("ix_fk_claim_encounter").on(table.hospitalId, table.branchId, table.patientId, table.encounterId),
  index("ix_fk_claim_created_by").on(table.hospitalId, table.createdBy),
  index("ix_fk_claim_assigned_to").on(table.hospitalId, table.assignedTo),
  index("ix_claim_queue_scope").on(table.hospitalId, table.branchId, table.claimStatus, table.createdAt),
  check("ck_claims_claim_type", sql`${table.claimType} IN ('CASHLESS', 'REIMBURSEMENT', 'GOVERNMENT', 'CORPORATE', 'TPA', 'OTHER')`),
  check("ck_claims_claim_stage", sql`${table.claimStage} IN ('REGISTERED', 'ELIGIBILITY_VERIFICATION', 'PRE_AUTH', 'TREATMENT', 'SUBMISSION', 'QUERY', 'APPROVAL', 'REJECTION', 'SETTLEMENT', 'CLOSED')`),
  check("ck_claims_claim_status", sql`${table.claimStatus} IN ('DRAFT', 'PENDING', 'IN_PROGRESS', 'APPROVED', 'QUERY', 'REJECTED', 'SETTLED', 'CANCELLED')`),
  check("ck_claims_estimated_amount_nonnegative", sql`${table.estimatedAmount} >= 0`),
  check("ck_claims_claimed_amount_nonnegative", sql`${table.claimedAmount} >= 0`),
  check("ck_claims_approved_amount_nonnegative", sql`${table.approvedAmount} >= 0`),
  check("ck_claims_rejected_amount_nonnegative", sql`${table.rejectedAmount} >= 0`),
  check("ck_claims_patient_payable_amount_nonnegative", sql`${table.patientPayableAmount} >= 0`),
  check("ck_claims_admission_date_discharge_date", sql`${table.dischargeDate} >= ${table.admissionDate}`),
  check("ck_claims_version", sql`${table.version} > 0`),
  foreignKey({ name: "fk_claim_patient", columns: [table.hospitalId, table.patientId], foreignColumns: [patients.hospitalId, patients.patientId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_patient_insurance", columns: [table.hospitalId, table.patientId, table.patientInsuranceId], foreignColumns: [patientInsurance.hospitalId, patientInsurance.patientId, patientInsurance.patientInsuranceId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_encounter", columns: [table.hospitalId, table.branchId, table.patientId, table.encounterId], foreignColumns: [encounters.hospitalId, encounters.branchId, encounters.patientId, encounters.encounterId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_created_by", columns: [table.hospitalId, table.createdBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_assigned_to", columns: [table.hospitalId, table.assignedTo], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claims_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claims_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const eligibilityChecks = pgTable("eligibility_checks", {
  eligibilityId: bigint("eligibility_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  claimId: bigint("claim_id", { mode: "bigint" }).notNull(),
  requestNo: varchar("request_no", { length: 80 }).notNull(),
  requestedAt: timestamp("requested_at", { withTimezone: true }).defaultNow(),
  verifiedAt: timestamp("verified_at", { withTimezone: true }),
  method: varchar("method", { length: 50 }).default("MANUAL"),
  eligibilityStatus: varchar("eligibility_status", { length: 50 }).default("PENDING"),
  coverageAvailable: numeric("coverage_available", { precision: 15, scale: 2 }),
  coverageUsed: numeric("coverage_used", { precision: 15, scale: 2 }),
  coverageBalance: numeric("coverage_balance", { precision: 15, scale: 2 }),
  responseCode: varchar("response_code", { length: 100 }),
  responseMessage: text("response_message"),
  verifiedBy: bigint("verified_by", { mode: "bigint" }),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  check("ck_eligibility_checks_coverage_available_finite", sql`${table.coverageAvailable} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_eligibility_checks_coverage_used_finite", sql`${table.coverageUsed} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_eligibility_checks_coverage_balance_finite", sql`${table.coverageBalance} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_eligibility_checks_request_no").on(table.requestNo),
  unique("uq_eligibility_checks_hospital_id_eligibility_id").on(table.hospitalId, table.eligibilityId),
  unique("uq_eligibility_checks_hospital_id_branch_id_eligibility_id").on(table.hospitalId, table.branchId, table.eligibilityId),
  index("ix_fk_elig_claim").on(table.hospitalId, table.branchId, table.claimId),
  index("ix_fk_elig_user").on(table.hospitalId, table.verifiedBy),
  check("ck_eligibility_checks_method", sql`${table.method} IN ('MANUAL', 'API', 'PORTAL', 'AI_AUTOMATION')`),
  check("ck_eligibility_checks_eligibility_status", sql`${table.eligibilityStatus} IN ('PENDING', 'ELIGIBLE', 'PARTIALLY_ELIGIBLE', 'NOT_ELIGIBLE', 'ERROR')`),
  check("ck_eligibility_checks_coverage_available_nonnegative", sql`${table.coverageAvailable} >= 0`),
  check("ck_eligibility_checks_coverage_used_nonnegative", sql`${table.coverageUsed} >= 0`),
  check("ck_eligibility_checks_coverage_balance_nonnegative", sql`${table.coverageBalance} >= 0`),
  foreignKey({ name: "fk_elig_claim", columns: [table.hospitalId, table.branchId, table.claimId], foreignColumns: [claims.hospitalId, claims.branchId, claims.claimId] }).onDelete("restrict"),
  foreignKey({ name: "fk_elig_user", columns: [table.hospitalId, table.verifiedBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_eligibility_checks_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_eligibility_checks_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const preAuthorizations = pgTable("pre_authorizations", {
  preauthId: bigint("preauth_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  claimId: bigint("claim_id", { mode: "bigint" }).notNull(),
  preauthNo: varchar("preauth_no", { length: 80 }).notNull(),
  requestedAt: timestamp("requested_at", { withTimezone: true }).defaultNow(),
  submittedAt: timestamp("submitted_at", { withTimezone: true }),
  responseAt: timestamp("response_at", { withTimezone: true }),
  authorizationNo: varchar("authorization_no", { length: 100 }),
  requestedAmount: numeric("requested_amount", { precision: 15, scale: 2 }),
  approvedAmount: numeric("approved_amount", { precision: 15, scale: 2 }),
  status: varchar("status", { length: 50 }).default("DRAFT"),
  queryText: text("query_text"),
  responseText: text("response_text"),
  submittedBy: bigint("submitted_by", { mode: "bigint" }),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  check("ck_pre_authorizations_requested_amount_finite", sql`${table.requestedAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_pre_authorizations_approved_amount_finite", sql`${table.approvedAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_pre_authorizations_preauth_no").on(table.preauthNo),
  unique("uq_pre_authorizations_hospital_id_preauth_id").on(table.hospitalId, table.preauthId),
  unique("uq_pre_authorizations_hospital_id_branch_id_preauth_id").on(table.hospitalId, table.branchId, table.preauthId),
  index("ix_fk_preauth_claim").on(table.hospitalId, table.branchId, table.claimId),
  index("ix_fk_preauth_user").on(table.hospitalId, table.submittedBy),
  check("ck_pre_authorizations_status", sql`${table.status} IN ('DRAFT', 'SUBMITTED', 'IN_REVIEW', 'APPROVED', 'QUERY', 'REJECTED', 'CANCELLED')`),
  check("ck_pre_authorizations_requested_amount_nonnegative", sql`${table.requestedAmount} >= 0`),
  check("ck_pre_authorizations_approved_amount_nonnegative", sql`${table.approvedAmount} >= 0`),
  foreignKey({ name: "fk_preauth_claim", columns: [table.hospitalId, table.branchId, table.claimId], foreignColumns: [claims.hospitalId, claims.branchId, claims.claimId] }).onDelete("restrict"),
  foreignKey({ name: "fk_preauth_user", columns: [table.hospitalId, table.submittedBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_pre_authorizations_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_pre_authorizations_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const claimDocuments = pgTable("claim_documents", {
  claimDocumentId: bigint("claim_document_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  claimId: bigint("claim_id", { mode: "bigint" }).notNull(),
  documentType: varchar("document_type", { length: 100 }).notNull(),
  documentName: varchar("document_name", { length: 255 }).notNull(),
  filePath: varchar("file_path", { length: 500 }),
  fileHash: varchar("file_hash", { length: 128 }),
  uploadedBy: bigint("uploaded_by", { mode: "bigint" }),
  uploadedAt: timestamp("uploaded_at", { withTimezone: true }).defaultNow(),
  verificationStatus: varchar("verification_status", { length: 50 }).default("PENDING"),
  remarks: text("remarks"),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  unique("uq_claim_documents_hospital_id_claim_document_id").on(table.hospitalId, table.claimDocumentId),
  unique("uq_claim_documents_hospital_id_branch_id_claim_document_id").on(table.hospitalId, table.branchId, table.claimDocumentId),
  unique("uq_claim_documents_hospital_id_branch_id_claim_id_claim_document_id").on(table.hospitalId, table.branchId, table.claimId, table.claimDocumentId),
  index("ix_fk_cd_user").on(table.hospitalId, table.uploadedBy),
  check("ck_claim_documents_verification_status", sql`${table.verificationStatus} IN ('PENDING', 'VERIFIED', 'REJECTED')`),
  foreignKey({ name: "fk_cd_claim", columns: [table.hospitalId, table.branchId, table.claimId], foreignColumns: [claims.hospitalId, claims.branchId, claims.claimId] }).onDelete("restrict"),
  foreignKey({ name: "fk_cd_user", columns: [table.hospitalId, table.uploadedBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_documents_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_documents_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const claimSubmissions = pgTable("claim_submissions", {
  submissionId: bigint("submission_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  claimId: bigint("claim_id", { mode: "bigint" }).notNull(),
  submissionNo: varchar("submission_no", { length: 80 }).notNull(),
  submittedTo: varchar("submitted_to", { length: 50 }).notNull(),
  submittedAt: timestamp("submitted_at", { withTimezone: true }).defaultNow(),
  externalReferenceNo: varchar("external_reference_no", { length: 150 }),
  submissionMethod: varchar("submission_method", { length: 50 }).default("MANUAL"),
  submittedAmount: numeric("submitted_amount", { precision: 15, scale: 2 }),
  status: varchar("status", { length: 50 }).default("SUBMITTED"),
  responseAt: timestamp("response_at", { withTimezone: true }),
  responseMessage: text("response_message"),
  submittedBy: bigint("submitted_by", { mode: "bigint" }),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  check("ck_claim_submissions_submitted_amount_finite", sql`${table.submittedAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_claim_submissions_submission_no").on(table.submissionNo),
  unique("uq_claim_submissions_hospital_id_submission_id").on(table.hospitalId, table.submissionId),
  unique("uq_claim_submissions_hospital_id_branch_id_submission_id").on(table.hospitalId, table.branchId, table.submissionId),
  unique("uq_claim_submissions_hospital_id_branch_id_claim_id_submission_id").on(table.hospitalId, table.branchId, table.claimId, table.submissionId),
  index("ix_fk_cs_user").on(table.hospitalId, table.submittedBy),
  check("ck_claim_submissions_submitted_to", sql`${table.submittedTo} IN ('INSURER', 'TPA', 'GOVERNMENT_PORTAL', 'CORPORATE', 'OTHER')`),
  check("ck_claim_submissions_submission_method", sql`${table.submissionMethod} IN ('MANUAL', 'API', 'PORTAL', 'AI_AUTOMATION')`),
  check("ck_claim_submissions_status", sql`${table.status} IN ('SUBMITTED', 'ACKNOWLEDGED', 'QUERY', 'APPROVED', 'REJECTED')`),
  check("ck_claim_submissions_submitted_amount_nonnegative", sql`${table.submittedAmount} >= 0`),
  foreignKey({ name: "fk_cs_claim", columns: [table.hospitalId, table.branchId, table.claimId], foreignColumns: [claims.hospitalId, claims.branchId, claims.claimId] }).onDelete("restrict"),
  foreignKey({ name: "fk_cs_user", columns: [table.hospitalId, table.submittedBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_submissions_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_submissions_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const claimQueries = pgTable("claim_queries", {
  queryId: bigint("query_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  claimId: bigint("claim_id", { mode: "bigint" }).notNull(),
  submissionId: bigint("submission_id", { mode: "bigint" }),
  queryNo: varchar("query_no", { length: 80 }).notNull(),
  queryDate: timestamp("query_date", { withTimezone: true }).defaultNow(),
  queryFrom: varchar("query_from", { length: 150 }),
  queryText: text("query_text").notNull(),
  responseText: text("response_text"),
  responseDueDate: date("response_due_date"),
  respondedAt: timestamp("responded_at", { withTimezone: true }),
  status: varchar("status", { length: 50 }).default("OPEN"),
  assignedTo: bigint("assigned_to", { mode: "bigint" }),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  unique("uq_claim_queries_query_no").on(table.queryNo),
  unique("uq_claim_queries_hospital_id_query_id").on(table.hospitalId, table.queryId),
  unique("uq_claim_queries_hospital_id_branch_id_query_id").on(table.hospitalId, table.branchId, table.queryId),
  index("ix_fk_cq_claim").on(table.hospitalId, table.branchId, table.claimId),
  index("ix_fk_cq_submission").on(table.hospitalId, table.branchId, table.claimId, table.submissionId),
  index("ix_fk_cq_user").on(table.hospitalId, table.assignedTo),
  check("ck_claim_queries_status", sql`${table.status} IN ('OPEN', 'RESPONDED', 'RESOLVED', 'ESCALATED')`),
  foreignKey({ name: "fk_cq_claim", columns: [table.hospitalId, table.branchId, table.claimId], foreignColumns: [claims.hospitalId, claims.branchId, claims.claimId] }).onDelete("restrict"),
  foreignKey({ name: "fk_cq_submission", columns: [table.hospitalId, table.branchId, table.claimId, table.submissionId], foreignColumns: [claimSubmissions.hospitalId, claimSubmissions.branchId, claimSubmissions.claimId, claimSubmissions.submissionId] }).onDelete("restrict"),
  foreignKey({ name: "fk_cq_user", columns: [table.hospitalId, table.assignedTo], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_queries_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_queries_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const claimDecisions = pgTable("claim_decisions", {
  decisionId: bigint("decision_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  claimId: bigint("claim_id", { mode: "bigint" }).notNull(),
  decisionType: varchar("decision_type", { length: 50 }).notNull(),
  decisionDate: timestamp("decision_date", { withTimezone: true }).defaultNow(),
  approvedAmount: numeric("approved_amount", { precision: 15, scale: 2 }),
  reason: text("reason"),
  externalReferenceNo: varchar("external_reference_no", { length: 150 }),
  decidedBy: bigint("decided_by", { mode: "bigint" }),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  check("ck_claim_decisions_approved_amount_finite", sql`${table.approvedAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_claim_decisions_hospital_id_decision_id").on(table.hospitalId, table.decisionId),
  unique("uq_claim_decisions_hospital_id_branch_id_decision_id").on(table.hospitalId, table.branchId, table.decisionId),
  index("ix_fk_dec_claim").on(table.hospitalId, table.branchId, table.claimId),
  index("ix_fk_dec_user").on(table.hospitalId, table.decidedBy),
  check("ck_claim_decisions_decision_type", sql`${table.decisionType} IN ('APPROVAL', 'PARTIAL_APPROVAL', 'QUERY', 'REJECTION')`),
  check("ck_claim_decisions_approved_amount_nonnegative", sql`${table.approvedAmount} >= 0`),
  foreignKey({ name: "fk_dec_claim", columns: [table.hospitalId, table.branchId, table.claimId], foreignColumns: [claims.hospitalId, claims.branchId, claims.claimId] }).onDelete("restrict"),
  foreignKey({ name: "fk_dec_user", columns: [table.hospitalId, table.decidedBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_decisions_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_decisions_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const settlements = pgTable("settlements", {
  settlementId: bigint("settlement_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  claimId: bigint("claim_id", { mode: "bigint" }).notNull(),
  settlementNo: varchar("settlement_no", { length: 80 }).notNull(),
  settlementDate: timestamp("settlement_date", { withTimezone: true }),
  approvedAmount: numeric("approved_amount", { precision: 15, scale: 2 }),
  deductibleAmount: numeric("deductible_amount", { precision: 15, scale: 2 }),
  copayAmount: numeric("copay_amount", { precision: 15, scale: 2 }),
  nonPayableAmount: numeric("non_payable_amount", { precision: 15, scale: 2 }),
  patientPayableAmount: numeric("patient_payable_amount", { precision: 15, scale: 2 }),
  insurerPayableAmount: numeric("insurer_payable_amount", { precision: 15, scale: 2 }),
  paymentMode: varchar("payment_mode", { length: 50 }),
  transactionReference: varchar("transaction_reference", { length: 150 }),
  status: varchar("status", { length: 50 }).default("PENDING"),
  postedBy: bigint("posted_by", { mode: "bigint" }),
  remarks: text("remarks"),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  check("ck_settlements_approved_amount_finite", sql`${table.approvedAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_settlements_deductible_amount_finite", sql`${table.deductibleAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_settlements_copay_amount_finite", sql`${table.copayAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_settlements_non_payable_amount_finite", sql`${table.nonPayableAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_settlements_patient_payable_amount_finite", sql`${table.patientPayableAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_settlements_insurer_payable_amount_finite", sql`${table.insurerPayableAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_settlements_settlement_no").on(table.settlementNo),
  unique("uq_settlements_hospital_id_settlement_id").on(table.hospitalId, table.settlementId),
  unique("uq_settlements_hospital_id_branch_id_settlement_id").on(table.hospitalId, table.branchId, table.settlementId),
  index("ix_fk_set_claim").on(table.hospitalId, table.branchId, table.claimId),
  index("ix_fk_set_user").on(table.hospitalId, table.postedBy),
  check("ck_settlements_payment_mode", sql`${table.paymentMode} IN ('NEFT', 'RTGS', 'IMPS', 'CHEQUE', 'CASH', 'UPI', 'OTHER')`),
  check("ck_settlements_status", sql`${table.status} IN ('PENDING', 'PARTIAL', 'SETTLED', 'FAILED', 'CANCELLED')`),
  check("ck_settlements_approved_amount_nonnegative", sql`${table.approvedAmount} >= 0`),
  check("ck_settlements_deductible_amount_nonnegative", sql`${table.deductibleAmount} >= 0`),
  check("ck_settlements_copay_amount_nonnegative", sql`${table.copayAmount} >= 0`),
  check("ck_settlements_non_payable_amount_nonnegative", sql`${table.nonPayableAmount} >= 0`),
  check("ck_settlements_patient_payable_amount_nonnegative", sql`${table.patientPayableAmount} >= 0`),
  check("ck_settlements_insurer_payable_amount_nonnegative", sql`${table.insurerPayableAmount} >= 0`),
  foreignKey({ name: "fk_set_claim", columns: [table.hospitalId, table.branchId, table.claimId], foreignColumns: [claims.hospitalId, claims.branchId, claims.claimId] }).onDelete("restrict"),
  foreignKey({ name: "fk_set_user", columns: [table.hospitalId, table.postedBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_settlements_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_settlements_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const invoices = pgTable("invoices", {
  invoiceId: bigint("invoice_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  patientId: bigint("patient_id", { mode: "bigint" }).notNull(),
  encounterId: bigint("encounter_id", { mode: "bigint" }),
  claimId: bigint("claim_id", { mode: "bigint" }),
  invoiceNo: varchar("invoice_no", { length: 80 }).notNull(),
  invoiceDate: timestamp("invoice_date", { withTimezone: true }).defaultNow(),
  grossAmount: numeric("gross_amount", { precision: 15, scale: 2 }),
  discountAmount: numeric("discount_amount", { precision: 15, scale: 2 }),
  taxAmount: numeric("tax_amount", { precision: 15, scale: 2 }),
  netAmount: numeric("net_amount", { precision: 15, scale: 2 }),
  insuranceAmount: numeric("insurance_amount", { precision: 15, scale: 2 }),
  patientAmount: numeric("patient_amount", { precision: 15, scale: 2 }),
  status: varchar("status", { length: 50 }).default("DRAFT"),
  createdBy: bigint("created_by", { mode: "bigint" }),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  check("ck_invoices_gross_amount_finite", sql`${table.grossAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_invoices_discount_amount_finite", sql`${table.discountAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_invoices_tax_amount_finite", sql`${table.taxAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_invoices_net_amount_finite", sql`${table.netAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_invoices_insurance_amount_finite", sql`${table.insuranceAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_invoices_patient_amount_finite", sql`${table.patientAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_invoices_invoice_no").on(table.invoiceNo),
  unique("uq_invoices_hospital_id_invoice_id").on(table.hospitalId, table.invoiceId),
  unique("uq_invoices_hospital_id_branch_id_invoice_id").on(table.hospitalId, table.branchId, table.invoiceId),
  index("ix_fk_inv_patient").on(table.hospitalId, table.patientId),
  index("ix_fk_inv_encounter").on(table.hospitalId, table.branchId, table.patientId, table.encounterId),
  index("ix_fk_inv_claim").on(table.hospitalId, table.branchId, table.patientId, table.claimId),
  index("ix_fk_inv_user").on(table.hospitalId, table.createdBy),
  check("ck_invoices_status", sql`${table.status} IN ('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED')`),
  check("ck_invoices_gross_amount_nonnegative", sql`${table.grossAmount} >= 0`),
  check("ck_invoices_discount_amount_nonnegative", sql`${table.discountAmount} >= 0`),
  check("ck_invoices_tax_amount_nonnegative", sql`${table.taxAmount} >= 0`),
  check("ck_invoices_net_amount_nonnegative", sql`${table.netAmount} >= 0`),
  check("ck_invoices_insurance_amount_nonnegative", sql`${table.insuranceAmount} >= 0`),
  check("ck_invoices_patient_amount_nonnegative", sql`${table.patientAmount} >= 0`),
  foreignKey({ name: "fk_inv_patient", columns: [table.hospitalId, table.patientId], foreignColumns: [patients.hospitalId, patients.patientId] }).onDelete("restrict"),
  foreignKey({ name: "fk_inv_encounter", columns: [table.hospitalId, table.branchId, table.patientId, table.encounterId], foreignColumns: [encounters.hospitalId, encounters.branchId, encounters.patientId, encounters.encounterId] }).onDelete("restrict"),
  foreignKey({ name: "fk_inv_claim", columns: [table.hospitalId, table.branchId, table.patientId, table.claimId], foreignColumns: [claims.hospitalId, claims.branchId, claims.patientId, claims.claimId] }).onDelete("restrict"),
  foreignKey({ name: "fk_inv_user", columns: [table.hospitalId, table.createdBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_invoices_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_invoices_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const invoiceItems = pgTable("invoice_items", {
  invoiceItemId: bigint("invoice_item_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  invoiceId: bigint("invoice_id", { mode: "bigint" }).notNull(),
  serviceId: bigint("service_id", { mode: "bigint" }),
  description: varchar("description", { length: 255 }).notNull(),
  quantity: numeric("quantity", { precision: 10, scale: 2 }).default("1"),
  unitPrice: numeric("unit_price", { precision: 15, scale: 2 }),
  discountAmount: numeric("discount_amount", { precision: 15, scale: 2 }),
  taxAmount: numeric("tax_amount", { precision: 15, scale: 2 }),
  netAmount: numeric("net_amount", { precision: 15, scale: 2 }),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  check("ck_invoice_items_quantity_finite", sql`${table.quantity} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_invoice_items_unit_price_finite", sql`${table.unitPrice} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_invoice_items_discount_amount_finite", sql`${table.discountAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_invoice_items_tax_amount_finite", sql`${table.taxAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_invoice_items_net_amount_finite", sql`${table.netAmount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_invoice_items_hospital_id_invoice_item_id").on(table.hospitalId, table.invoiceItemId),
  unique("uq_invoice_items_hospital_id_branch_id_invoice_item_id").on(table.hospitalId, table.branchId, table.invoiceItemId),
  index("ix_fk_ii_invoice").on(table.hospitalId, table.branchId, table.invoiceId),
  index("ix_fk_ii_service").on(table.serviceId),
  check("ck_invoice_items_quantity_positive", sql`${table.quantity} > 0`),
  check("ck_invoice_items_unit_price_nonnegative", sql`${table.unitPrice} >= 0`),
  check("ck_invoice_items_discount_amount_nonnegative", sql`${table.discountAmount} >= 0`),
  check("ck_invoice_items_tax_amount_nonnegative", sql`${table.taxAmount} >= 0`),
  check("ck_invoice_items_net_amount_nonnegative", sql`${table.netAmount} >= 0`),
  foreignKey({ name: "fk_ii_invoice", columns: [table.hospitalId, table.branchId, table.invoiceId], foreignColumns: [invoices.hospitalId, invoices.branchId, invoices.invoiceId] }).onDelete("restrict"),
  foreignKey({ name: "fk_ii_service", columns: [table.serviceId], foreignColumns: [treatmentServices.serviceId] }).onDelete("restrict"),
  foreignKey({ name: "fk_invoice_items_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_invoice_items_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const payments = pgTable("payments", {
  paymentId: bigint("payment_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  invoiceId: bigint("invoice_id", { mode: "bigint" }).notNull(),
  paymentNo: varchar("payment_no", { length: 80 }).notNull(),
  paymentDate: timestamp("payment_date", { withTimezone: true }).defaultNow(),
  amount: numeric("amount", { precision: 15, scale: 2 }).notNull(),
  paymentType: varchar("payment_type", { length: 50 }).default("PATIENT"),
  paymentMode: varchar("payment_mode", { length: 50 }).notNull(),
  transactionReference: varchar("transaction_reference", { length: 150 }),
  status: varchar("status", { length: 50 }).default("SUCCESS"),
  receivedBy: bigint("received_by", { mode: "bigint" }),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  check("ck_payments_amount_finite", sql`${table.amount} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_payments_payment_no").on(table.paymentNo),
  unique("uq_payments_hospital_id_payment_id").on(table.hospitalId, table.paymentId),
  unique("uq_payments_hospital_id_branch_id_payment_id").on(table.hospitalId, table.branchId, table.paymentId),
  index("ix_fk_payment_invoice").on(table.hospitalId, table.branchId, table.invoiceId),
  index("ix_fk_payment_user").on(table.hospitalId, table.receivedBy),
  check("ck_payments_payment_type", sql`${table.paymentType} IN ('PATIENT', 'INSURER', 'TPA', 'GOVERNMENT', 'CORPORATE', 'OTHER')`),
  check("ck_payments_payment_mode", sql`${table.paymentMode} IN ('CASH', 'CARD', 'UPI', 'NET_BANKING', 'NEFT', 'RTGS', 'IMPS', 'CHEQUE', 'OTHER')`),
  check("ck_payments_status", sql`${table.status} IN ('SUCCESS', 'PENDING', 'FAILED', 'REFUNDED')`),
  check("ck_payments_amount_nonnegative", sql`${table.amount} >= 0`),
  foreignKey({ name: "fk_payment_invoice", columns: [table.hospitalId, table.branchId, table.invoiceId], foreignColumns: [invoices.hospitalId, invoices.branchId, invoices.invoiceId] }).onDelete("restrict"),
  foreignKey({ name: "fk_payment_user", columns: [table.hospitalId, table.receivedBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_payments_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_payments_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const notifications = pgTable("notifications", {
  notificationId: bigint("notification_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  userId: bigint("user_id", { mode: "bigint" }),
  patientId: bigint("patient_id", { mode: "bigint" }),
  notificationType: varchar("notification_type", { length: 50 }).notNull(),
  subject: varchar("subject", { length: 255 }),
  message: text("message").notNull(),
  referenceType: varchar("reference_type", { length: 80 }),
  referenceId: bigint("reference_id", { mode: "bigint" }),
  status: varchar("status", { length: 50 }).default("QUEUED"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  sentAt: timestamp("sent_at", { withTimezone: true }),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }),
}, (table) => [
  unique("uq_notifications_hospital_id_notification_id").on(table.hospitalId, table.notificationId),
  unique("uq_notifications_hospital_id_branch_id_notification_id").on(table.hospitalId, table.branchId, table.notificationId),
  index("ix_fk_notif_user").on(table.hospitalId, table.userId),
  index("ix_fk_notif_patient").on(table.hospitalId, table.patientId),
  check("ck_notifications_notification_type", sql`${table.notificationType} IN ('EMAIL', 'SMS', 'WHATSAPP', 'IN_APP')`),
  check("ck_notifications_status", sql`${table.status} IN ('QUEUED', 'SENT', 'FAILED', 'READ')`),
  foreignKey({ name: "fk_notif_user", columns: [table.hospitalId, table.userId], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_notif_patient", columns: [table.hospitalId, table.patientId], foreignColumns: [patients.hospitalId, patients.patientId] }).onDelete("restrict"),
  foreignKey({ name: "fk_notifications_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_notifications_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const workflowDefinitions = pgTable("workflow_definitions", {
  workflowId: bigint("workflow_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  workflowCode: varchar("workflow_code", { length: 100 }).notNull(),
  workflowName: varchar("workflow_name", { length: 200 }).notNull(),
  n8nWorkflowId: varchar("n8n_workflow_id", { length: 150 }),
  description: text("description"),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
}, (table) => [
  unique("uq_workflow_definitions_workflow_code").on(table.workflowCode),
  check("ck_workflow_definitions_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
]);

export const workflowRuns = pgTable("workflow_runs", {
  workflowRunId: bigint("workflow_run_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  workflowId: bigint("workflow_id", { mode: "bigint" }).notNull(),
  claimId: bigint("claim_id", { mode: "bigint" }),
  patientId: bigint("patient_id", { mode: "bigint" }),
  executionId: varchar("execution_id", { length: 150 }),
  startedAt: timestamp("started_at", { withTimezone: true }).defaultNow(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  status: varchar("status", { length: 50 }).default("RUNNING"),
  errorMessage: text("error_message"),
  inputJson: jsonb("input_json"),
  outputJson: jsonb("output_json"),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  unique("uq_workflow_runs_hospital_id_workflow_run_id").on(table.hospitalId, table.workflowRunId),
  unique("uq_workflow_runs_hospital_id_branch_id_workflow_run_id").on(table.hospitalId, table.branchId, table.workflowRunId),
  index("ix_fk_wr_workflow").on(table.workflowId),
  index("ix_fk_wr_claim").on(table.hospitalId, table.branchId, table.patientId, table.claimId),
  index("ix_fk_wr_patient").on(table.hospitalId, table.patientId),
  check("ck_workflow_runs_status", sql`${table.status} IN ('RUNNING', 'SUCCESS', 'FAILED', 'WAITING', 'CANCELLED')`),
  check("ck_workflow_claim_patient", sql`${table.claimId} IS NULL OR ${table.patientId} IS NOT NULL`),
  check("ck_workflow_runs_started_at_finished_at", sql`${table.finishedAt} >= ${table.startedAt}`),
  foreignKey({ name: "fk_wr_workflow", columns: [table.workflowId], foreignColumns: [workflowDefinitions.workflowId] }).onDelete("restrict"),
  foreignKey({ name: "fk_wr_claim", columns: [table.hospitalId, table.branchId, table.patientId, table.claimId], foreignColumns: [claims.hospitalId, claims.branchId, claims.patientId, claims.claimId] }).onDelete("restrict"),
  foreignKey({ name: "fk_wr_patient", columns: [table.hospitalId, table.patientId], foreignColumns: [patients.hospitalId, patients.patientId] }).onDelete("restrict"),
  foreignKey({ name: "fk_workflow_runs_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_workflow_runs_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const aiAgentRuns = pgTable("ai_agent_runs", {
  agentRunId: bigint("agent_run_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  workflowRunId: bigint("workflow_run_id", { mode: "bigint" }),
  agentName: varchar("agent_name", { length: 150 }).notNull(),
  taskType: varchar("task_type", { length: 150 }),
  inputJson: jsonb("input_json"),
  outputJson: jsonb("output_json"),
  confidenceScore: numeric("confidence_score", { precision: 5, scale: 2 }),
  status: varchar("status", { length: 50 }).default("STARTED"),
  startedAt: timestamp("started_at", { withTimezone: true }).defaultNow(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
  errorMessage: text("error_message"),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  check("ck_ai_agent_runs_confidence_score_finite", sql`${table.confidenceScore} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_ai_agent_runs_hospital_id_agent_run_id").on(table.hospitalId, table.agentRunId),
  unique("uq_ai_agent_runs_hospital_id_branch_id_agent_run_id").on(table.hospitalId, table.branchId, table.agentRunId),
  index("ix_fk_agent_workflow").on(table.hospitalId, table.branchId, table.workflowRunId),
  check("ck_ai_agent_runs_status", sql`${table.status} IN ('STARTED', 'SUCCESS', 'FAILED', 'REVIEW_REQUIRED')`),
  check("ck_ai_agent_runs_confidence_score_range", sql`${table.confidenceScore} BETWEEN 0 AND 100`),
  check("ck_ai_agent_runs_started_at_finished_at", sql`${table.finishedAt} >= ${table.startedAt}`),
  foreignKey({ name: "fk_agent_workflow", columns: [table.hospitalId, table.branchId, table.workflowRunId], foreignColumns: [workflowRuns.hospitalId, workflowRuns.branchId, workflowRuns.workflowRunId] }).onDelete("restrict"),
  foreignKey({ name: "fk_ai_agent_runs_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_ai_agent_runs_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const auditLogs = pgTable("audit_logs", {
  auditId: bigint("audit_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  userId: bigint("user_id", { mode: "bigint" }),
  moduleName: varchar("module_name", { length: 100 }).notNull(),
  entityType: varchar("entity_type", { length: 100 }),
  entityId: bigint("entity_id", { mode: "bigint" }),
  actionName: varchar("action_name", { length: 50 }).notNull(),
  oldData: jsonb("old_data"),
  newData: jsonb("new_data"),
  ipAddress: varchar("ip_address", { length: 45 }),
  userAgent: varchar("user_agent", { length: 500 }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }),
  branchId: bigint("branch_id", { mode: "bigint" }),
}, (table) => [
  check("ck_audit_logs_branch_scope", sql`${table.branchId} IS NULL OR ${table.hospitalId} IS NOT NULL`),
  unique("uq_audit_logs_hospital_id_audit_id").on(table.hospitalId, table.auditId),
  unique("uq_audit_logs_hospital_id_branch_id_audit_id").on(table.hospitalId, table.branchId, table.auditId),
  index("idx_audit_module").on(table.moduleName),
  index("idx_audit_created").on(table.createdAt),
  index("ix_fk_audit_user").on(table.hospitalId, table.userId),
  check("ck_audit_logs_actor_scope", sql`${table.userId} IS NULL OR ${table.hospitalId} IS NOT NULL`),
  foreignKey({ name: "fk_audit_user", columns: [table.hospitalId, table.userId], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_audit_logs_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_audit_logs_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const loginLogs = pgTable("login_logs", {
  loginLogId: bigint("login_log_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  userId: bigint("user_id", { mode: "bigint" }),
  loginAt: timestamp("login_at", { withTimezone: true }).defaultNow(),
  logoutAt: timestamp("logout_at", { withTimezone: true }),
  ipAddress: varchar("ip_address", { length: 45 }),
  userAgent: varchar("user_agent", { length: 500 }),
  loginStatus: varchar("login_status", { length: 50 }).default("SUCCESS"),
  failureReason: varchar("failure_reason", { length: 255 }),
  hospitalId: bigint("hospital_id", { mode: "bigint" }),
  branchId: bigint("branch_id", { mode: "bigint" }),
}, (table) => [
  check("ck_login_logs_branch_scope", sql`${table.branchId} IS NULL OR ${table.hospitalId} IS NOT NULL`),
  unique("uq_login_logs_hospital_id_login_log_id").on(table.hospitalId, table.loginLogId),
  unique("uq_login_logs_hospital_id_branch_id_login_log_id").on(table.hospitalId, table.branchId, table.loginLogId),
  index("ix_fk_login_user").on(table.hospitalId, table.userId),
  check("ck_login_logs_login_status", sql`${table.loginStatus} IN ('SUCCESS', 'FAILED', 'LOCKED')`),
  check("ck_login_logs_actor_scope", sql`${table.userId} IS NULL OR ${table.hospitalId} IS NOT NULL`),
  foreignKey({ name: "fk_login_user", columns: [table.hospitalId, table.userId], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_login_logs_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_login_logs_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const coverageRules = pgTable("coverage_rules", {
  coverageRuleId: bigint("coverage_rule_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  policyId: bigint("policy_id", { mode: "bigint" }).notNull(),
  serviceId: bigint("service_id", { mode: "bigint" }),
  coveragePercent: numeric("coverage_percent", { precision: 5, scale: 2 }),
  fixedLimit: numeric("fixed_limit", { precision: 15, scale: 2 }),
  waitingDays: integer("waiting_days").default(0),
  authorizationRequired: boolean("authorization_required").default(false),
  notes: text("notes"),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
}, (table) => [
  check("ck_coverage_rules_coverage_percent_finite", sql`${table.coveragePercent} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  check("ck_coverage_rules_fixed_limit_finite", sql`${table.fixedLimit} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  index("ix_fk_cr_policy").on(table.policyId),
  index("ix_fk_cr_service").on(table.serviceId),
  check("ck_coverage_rules_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
  check("ck_coverage_rules_coverage_percent_range", sql`${table.coveragePercent} BETWEEN 0 AND 100`),
  check("ck_coverage_rules_fixed_limit_nonnegative", sql`${table.fixedLimit} >= 0`),
  check("ck_coverage_rules_waiting_days", sql`${table.waitingDays} >= 0`),
  foreignKey({ name: "fk_cr_policy", columns: [table.policyId], foreignColumns: [insurancePolicies.policyId] }).onDelete("restrict"),
  foreignKey({ name: "fk_cr_service", columns: [table.serviceId], foreignColumns: [treatmentServices.serviceId] }).onDelete("restrict"),
]);

export const corporateAccounts = pgTable("corporate_accounts", {
  corporateId: bigint("corporate_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  corporateCode: varchar("corporate_code", { length: 50 }).notNull(),
  corporateName: varchar("corporate_name", { length: 200 }).notNull(),
  contactPerson: varchar("contact_person", { length: 150 }),
  phone: varchar("phone", { length: 30 }),
  email: varchar("email", { length: 150 }),
  contractStart: date("contract_start"),
  contractEnd: date("contract_end"),
  creditLimit: numeric("credit_limit", { precision: 15, scale: 2 }),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
}, (table) => [
  check("ck_corporate_accounts_credit_limit_finite", sql`${table.creditLimit} NOT IN ('NaN'::numeric, 'Infinity'::numeric, '-Infinity'::numeric)`),
  unique("uq_corporate_accounts_corporate_code").on(table.corporateCode),
  unique("uq_corporate_accounts_hospital_id_corporate_id").on(table.hospitalId, table.corporateId),
  check("ck_corporate_accounts_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
  check("ck_corporate_accounts_credit_limit_nonnegative", sql`${table.creditLimit} >= 0`),
  check("ck_corporate_accounts_contract_start_contract_end", sql`${table.contractEnd} >= ${table.contractStart}`),
  foreignKey({ name: "fk_corporate_accounts_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
]);

export const governmentSchemes = pgTable("government_schemes", {
  schemeId: bigint("scheme_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  schemeCode: varchar("scheme_code", { length: 50 }).notNull(),
  schemeName: varchar("scheme_name", { length: 200 }).notNull(),
  authorityName: varchar("authority_name", { length: 200 }),
  stateName: varchar("state_name", { length: 100 }),
  portalUrl: varchar("portal_url", { length: 255 }),
  helpline: varchar("helpline", { length: 50 }),
  status: varchar("status", { length: 50 }).default("ACTIVE"),
}, (table) => [
  unique("uq_government_schemes_scheme_code").on(table.schemeCode),
  check("ck_government_schemes_status", sql`${table.status} IN ('ACTIVE', 'INACTIVE')`),
]);

export const claimGovernmentScheme = pgTable("claim_government_scheme", {
  claimId: bigint("claim_id", { mode: "bigint" }).notNull(),
  schemeId: bigint("scheme_id", { mode: "bigint" }).notNull(),
  beneficiaryId: varchar("beneficiary_id", { length: 100 }),
  packageCode: varchar("package_code", { length: 100 }),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
}, (table) => [
  primaryKey({ columns: [table.claimId, table.schemeId] }),
  index("ix_fk_cgs_claim").on(table.hospitalId, table.branchId, table.claimId),
  index("ix_fk_cgs_scheme").on(table.schemeId),
  foreignKey({ name: "fk_cgs_claim", columns: [table.hospitalId, table.branchId, table.claimId], foreignColumns: [claims.hospitalId, claims.branchId, claims.claimId] }).onDelete("restrict"),
  foreignKey({ name: "fk_cgs_scheme", columns: [table.schemeId], foreignColumns: [governmentSchemes.schemeId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_government_scheme_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_government_scheme_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
]);

export const branches = pgTable("branches", {
  branchId: bigint("branch_id", { mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchCode: varchar("branch_code", { length: 30 }).notNull(),
  name: varchar("name", { length: 150 }).notNull(),
  status: varchar("status", { length: 50 }).notNull().default("ACTIVE"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  unique("uq_branch_code").on(table.hospitalId, table.branchCode),
  unique("uq_branches_hospital_id_branch_id").on(table.hospitalId, table.branchId),
  check("ck_branches_status", sql`${table.status} IN ('ACTIVE','INACTIVE')`),
  foreignKey({ name: "fk_branches_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
]);

export const userBranchMemberships = pgTable("user_branch_memberships", {
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  userId: bigint("user_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
  roleId: bigint("role_id", { mode: "bigint" }).notNull(),
  status: varchar("status", { length: 50 }).notNull().default("ACTIVE"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  primaryKey({ columns: [table.hospitalId, table.userId, table.branchId, table.roleId] }),
  index("ix_fk_user_branch_memberships_branch").on(table.hospitalId, table.branchId),
  index("ix_fk_membership_user_role").on(table.hospitalId, table.userId, table.roleId),
  index("ix_fk_membership_role").on(table.roleId),
  check("ck_user_branch_memberships_status", sql`${table.status} IN ('ACTIVE','REVOKED')`),
  foreignKey({ name: "fk_user_branch_memberships_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_user_branch_memberships_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
  foreignKey({ name: "fk_membership_user_role", columns: [table.hospitalId, table.userId, table.roleId], foreignColumns: [userRoles.hospitalId, userRoles.userId, userRoles.roleId] }).onDelete("restrict"),
  foreignKey({ name: "fk_membership_role", columns: [table.roleId], foreignColumns: [roles.roleId] }).onDelete("restrict"),
]);

export const staffInvitations = pgTable("staff_invitations", {
  id: text("id").primaryKey(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
  roleId: bigint("role_id", { mode: "bigint" }).notNull(),
  email: varchar("email", { length: 150 }).notNull(),
  tokenHash: text("token_hash").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  status: varchar("status", { length: 50 }).notNull().default("PENDING"),
  createdBy: bigint("created_by", { mode: "bigint" }).notNull(),
  acceptedUserId: bigint("accepted_user_id", { mode: "bigint" }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  unique("uq_staff_invitation_token").on(table.tokenHash),
  unique("uq_staff_invitations_hospital_id_id").on(table.hospitalId, table.id),
  unique("uq_staff_invitations_hospital_id_branch_id_id").on(table.hospitalId, table.branchId, table.id),
  index("ix_fk_invitation_created_by").on(table.hospitalId, table.createdBy),
  index("ix_fk_invitation_accepted_user_id").on(table.hospitalId, table.acceptedUserId),
  index("ix_fk_invitation_role").on(table.roleId),
  check("ck_staff_invitations_status", sql`${table.status} IN ('PENDING','ACCEPTED','REVOKED')`),
  foreignKey({ name: "fk_staff_invitations_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_staff_invitations_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
  foreignKey({ name: "fk_invitation_created_by", columns: [table.hospitalId, table.createdBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_invitation_accepted_user_id", columns: [table.hospitalId, table.acceptedUserId], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
  foreignKey({ name: "fk_invitation_role", columns: [table.roleId], foreignColumns: [roles.roleId] }).onDelete("restrict"),
]);

export const claimEvents = pgTable("claim_events", {
  eventId: text("event_id").primaryKey(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
  claimId: bigint("claim_id", { mode: "bigint" }).notNull(),
  actorUserId: bigint("actor_user_id", { mode: "bigint" }).notNull(),
  eventType: varchar("event_type", { length: 100 }).notNull(),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  recordedAt: timestamp("recorded_at", { withTimezone: true }).notNull().defaultNow(),
  payload: jsonb("payload").notNull().default(sql`'{}'::jsonb`),
  idempotencyKey: varchar("idempotency_key", { length: 150 }).notNull(),
  fingerprint: text("fingerprint").notNull(),
  caseVersion: integer("case_version").notNull(),
}, (table) => [
  unique("uq_claim_event_key").on(table.hospitalId, table.claimId, table.idempotencyKey),
  unique("uq_claim_events_hospital_id_event_id").on(table.hospitalId, table.eventId),
  unique("uq_claim_events_hospital_id_branch_id_event_id").on(table.hospitalId, table.branchId, table.eventId),
  index("ix_fk_claim_events_claim").on(table.hospitalId, table.branchId, table.claimId),
  index("ix_fk_claim_events_actor").on(table.hospitalId, table.actorUserId),
  check("ck_claim_events_case_version", sql`${table.caseVersion} > 0`),
  foreignKey({ name: "fk_claim_events_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_events_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_events_claim", columns: [table.hospitalId, table.branchId, table.claimId], foreignColumns: [claims.hospitalId, claims.branchId, claims.claimId] }).onDelete("restrict"),
  foreignKey({ name: "fk_claim_events_actor", columns: [table.hospitalId, table.actorUserId], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
]);

export const documentRevisions = pgTable("document_revisions", {
  revisionId: text("revision_id").primaryKey(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
  claimId: bigint("claim_id", { mode: "bigint" }).notNull(),
  claimDocumentId: bigint("claim_document_id", { mode: "bigint" }).notNull(),
  revisionNumber: integer("revision_number").notNull(),
  storageKey: text("storage_key").notNull(),
  sha256: varchar("sha256", { length: 64 }).notNull(),
  sizeBytes: bigint("size_bytes", { mode: "bigint" }).notNull(),
  mimeType: varchar("mime_type", { length: 100 }).notNull(),
  originalName: varchar("original_name", { length: 255 }).notNull(),
  uploadedBy: bigint("uploaded_by", { mode: "bigint" }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  idempotencyKey: varchar("idempotency_key", { length: 150 }).notNull(),
}, (table) => [
  unique("uq_document_revision_number").on(table.hospitalId, table.claimDocumentId, table.revisionNumber),
  unique("uq_document_revision_key").on(table.hospitalId, table.claimId, table.idempotencyKey),
  unique("uq_document_storage_key").on(table.storageKey),
  unique("uq_document_revisions_hospital_id_revision_id").on(table.hospitalId, table.revisionId),
  unique("uq_document_revisions_hospital_id_branch_id_revision_id").on(table.hospitalId, table.branchId, table.revisionId),
  unique("uq_document_revisions_hospital_id_branch_id_claim_id_revision_id").on(table.hospitalId, table.branchId, table.claimId, table.revisionId),
  index("ix_fk_document_revision_parent").on(table.hospitalId, table.branchId, table.claimId, table.claimDocumentId),
  index("ix_fk_document_revision_uploader").on(table.hospitalId, table.uploadedBy),
  check("ck_document_revision_number", sql`${table.revisionNumber} > 0`),
  check("ck_document_size", sql`${table.sizeBytes} > 0 AND ${table.sizeBytes} <= 5242880`),
  check("ck_document_sha256", sql`${table.sha256} ~ '^[0-9a-f]{64}$'`),
  check("ck_document_mime", sql`${table.mimeType} IN ('application/pdf','image/png','image/jpeg','text/plain')`),
  foreignKey({ name: "fk_document_revisions_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_document_revisions_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
  foreignKey({ name: "fk_document_revision_claim", columns: [table.hospitalId, table.branchId, table.claimId], foreignColumns: [claims.hospitalId, claims.branchId, claims.claimId] }).onDelete("restrict"),
  foreignKey({ name: "fk_document_revision_parent", columns: [table.hospitalId, table.branchId, table.claimId, table.claimDocumentId], foreignColumns: [claimDocuments.hospitalId, claimDocuments.branchId, claimDocuments.claimId, claimDocuments.claimDocumentId] }).onDelete("restrict"),
  foreignKey({ name: "fk_document_revision_uploader", columns: [table.hospitalId, table.uploadedBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
]);

export const documentEvidence = pgTable("document_evidence", {
  evidenceId: text("evidence_id").primaryKey(),
  hospitalId: bigint("hospital_id", { mode: "bigint" }).notNull(),
  branchId: bigint("branch_id", { mode: "bigint" }).notNull(),
  claimId: bigint("claim_id", { mode: "bigint" }).notNull(),
  revisionId: text("revision_id").notNull(),
  pageNumber: integer("page_number"),
  fieldName: varchar("field_name", { length: 150 }).notNull(),
  sourceExcerpt: text("source_excerpt").notNull(),
  recordedBy: bigint("recorded_by", { mode: "bigint" }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  unique("uq_document_evidence_hospital_id_evidence_id").on(table.hospitalId, table.evidenceId),
  unique("uq_document_evidence_hospital_id_branch_id_evidence_id").on(table.hospitalId, table.branchId, table.evidenceId),
  index("ix_fk_document_evidence_revision").on(table.hospitalId, table.branchId, table.claimId, table.revisionId),
  index("ix_fk_document_evidence_recorder").on(table.hospitalId, table.recordedBy),
  check("ck_document_evidence_page", sql`${table.pageNumber} IS NULL OR ${table.pageNumber} > 0`),
  foreignKey({ name: "fk_document_evidence_hospital", columns: [table.hospitalId], foreignColumns: [hospitals.hospitalId] }).onDelete("restrict"),
  foreignKey({ name: "fk_document_evidence_branch", columns: [table.hospitalId, table.branchId], foreignColumns: [branches.hospitalId, branches.branchId] }).onDelete("restrict"),
  foreignKey({ name: "fk_document_evidence_revision", columns: [table.hospitalId, table.branchId, table.claimId, table.revisionId], foreignColumns: [documentRevisions.hospitalId, documentRevisions.branchId, documentRevisions.claimId, documentRevisions.revisionId] }).onDelete("restrict"),
  foreignKey({ name: "fk_document_evidence_recorder", columns: [table.hospitalId, table.recordedBy], foreignColumns: [users.hospitalId, users.userId] }).onDelete("restrict"),
]);
